logging:
  level:
    ROOT: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GameOnAddGameCodeEntity
    username: company
    password:

  jpa:
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
